server:
  port: ${PORT:8080}

spring:
  application:
    name: order-service
  threads:
    virtual:
      enabled: true
  ai:
    vertexai:
      gemini:
        transport: rest
        api-key: ${GEMINI_API_KEY:dummy_key}
        model: gemini-1.5-flash
