server:
  port: 8082

spring:
  application:
    name: order-service
  threads:
    virtual:
      enabled: true
  ai:
    vertexai:
      gemini:
        api-key: ${GEMINI_API_KEY:}
        model: gemini-1.5-flash
